### ISSUE TITLE
Providing a Linux-arm64 wheel

### ISSUE THREAD

**Issue by gouttegd** [ozekik/lightrdf#13]
LightRDF is available as a wheel on PyPI for many combinations of systems and architectures (Windows/MacOS/Linux…, i686/x86_64/arm64…). Thanks for that!

However, one particular combination that is missing is Linux/arm64. Any chance it could be added?

**Comment by ozekik** [comment]
Thank you for your suggestion!
I just added and published builds for linux on arm64 (aarch64).
Running `pip install lightrdf` should work for it now; please let me know if you have any trouble.

- https://pypi.org/project/lightrdf/0.3.1/#files
- https://github.com/ozekik/lightrdf/releases/tag/v0.3.1%2B001

**Comment by gouttegd** [comment]
Indeed, it’s working just fine. Thank you, it’s much appreciated!
